myboot:
  name: Prod Env

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/boot_db
    username: root
    password: maria
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: warn
    com.example.myapp: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  file:
    name: logs/prod.log

#a