myboot:
  name: Dev Env

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_diary?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_woogi
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: debug
    com.devdiary: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  file:
    name: logs/dev.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

#a