myboot:
  name: Prod Env

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_diary?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_woogi
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: warn
    com.example.myapp: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  file:
    name: logs/prod.log

#a